spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/squad3}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: true
    hibernate.ddl-auto: update
codenation:
  swagger:
    title: Backend squad3
    description: Api Rest to Logs
    version: 1.0
    package: br.com.codenation.desafio
  oauth:
    user:
      email: admin@admin.com
      password: admin
      name: Admin
    client:
       client-id: 312321312
       client-secret: 123456
       gran-types: password,authorization_code,refresh_token,implicit
       scopes: read,write,trust
