spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/squad3}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: true
    hibernate.ddl-auto: update
desafio:
  swagger:
    title: Backend squad3
    description: Api Rest to Logs
    version: 1.0
    package: br.com.codenation.desafio

