#debug: true
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/squad3}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: true
    hibernate.ddl-auto: update

authorization:
  email: ${AUTH_ADMIN_USER:admin@admin.com}
  password: ${AUTH_ADMIN_PASSWORD:admin}
  client:
    id: ${AUTH_CLIENT_ID:client-id}
    secret: ${AUTH_CLIENT_SECRET:client-secret}
    grant-types: ${AUTH_CLIENT_GRANT_TYPES:password, authorization_code, refresh_token, implicit}
    scopes: ${AUTH_CLIENT_SCOPES:read, write, trust}

swagger:
  title: Backend squad3
  description: Api rest Logs
  version: 0.0.1
  package: br.com.codenation.desafio.controller
  url: http://localhost:8080/oauth/token